apiVersion: v1
kind: Secret
metadata:
  name: gateway-postgresql
  namespace: demo
  labels:
    app: gateway-postgresql
type: Opaque
data:
  postgresql-password: NThiYzk1ZjJlYzZhYTMwYzhiMTA3YzRiZjhjZWZhMjM4M2YwNzM5NmFiMDQ1MjdiMjRkOWM2YjU0M2Y4
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-postgresql
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-postgresql
  template:
    metadata:
      labels:
        app: gateway-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:14.5
          env:
            - name: POSTGRES_USER
              value: gateway
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gateway-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-postgresql
  namespace: demo
spec:
  selector:
    app: gateway-postgresql
  ports:
    - port: 5432
